inherit_gem:
  rubocop-hk: config/default.yml

# Disable some strict rules for our own gem's tests
RSpec/DescribeClass:
  Enabled: false

RSpec/RepeatedExample:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/RemoveConst:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

Layout/LineLength:
  Max: 120  # Slightly more lenient for complex test expectations

Performance/ChainArrayAllocation:
  Enabled: false  # Allow for readable test code

Lint/ConstantDefinitionInBlock:
  Enabled: false  # Needed for testing module behavior

Lint/EmptyClass:
  Enabled: false  # Test classes can be empty

Rails/Output:
  Exclude:
    - "lib/rubocop/hk/command.rb"  # CLI tools need to output to stdout

Gemspec/RequireMFA:
  Enabled: false  # Disabled for automated publishing workflow