blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/hammadxcm/rubocop-hk#readme
    about: Check out our comprehensive documentation
  - name: 💬 Discussions
    url: https://github.com/hammadxcm/rubocop-hk/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔧 Configuration Help
    url: https://github.com/hammadxcm/rubocop-hk/discussions/categories/configuration-help
    about: Get help with RuboCop HK configuration