name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.2', '3.3', '3.4']
        rails-version: ['7.0', '7.1', '7.2', '8.0']
        exclude:
          # Rails 8.0 requires Ruby 3.2+
          - ruby-version: '3.1'
            rails-version: '8.0'
          # Rails 7.0 has Logger issues with newer Ruby versions  
          - ruby-version: '3.4'
            rails-version: '7.0'
    
    name: Ruby ${{ matrix.ruby-version }}, Rails ${{ matrix.rails-version }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    
    - name: Create test Rails app
      run: |
        # Require logger to avoid Rails Logger issues with newer Ruby versions
        ruby -e "require 'logger'" || true
        gem install rails -v "~> ${{ matrix.rails-version }}.0"
        RAILS_ENV=test rails new test_app --skip-git --skip-bundle --api
        cd test_app
        echo 'gem "rubocop-hk", path: ".."' >> Gemfile
        bundle install
    
    - name: Run tests
      run: bundle exec rspec --format progress --format RspecJunitFormatter --out tmp/rspec.xml
    
    - name: Test RuboCop configuration
      run: |
        cd test_app
        echo 'inherit_gem:
          rubocop-hk: config/default.yml
        
        AllCops:
          TargetRubyVersion: ${{ matrix.ruby-version }}
          TargetRailsVersion: ${{ matrix.rails-version }}' > .rubocop.yml
        bundle exec rubocop --version
        bundle exec rubocop app/ --format json --out tmp/rubocop.json || true
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-ruby-${{ matrix.ruby-version }}-rails-${{ matrix.rails-version }}
        path: |
          tmp/rspec.xml
          test_app/tmp/rubocop.json

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    
    - name: Run RuboCop on gem itself
      run: bundle exec rubocop --format github --parallel
    
    - name: Verify configuration files
      run: |
        bundle exec ruby -e "require 'yaml'; YAML.load_file('config/default.yml')"
        find config/ -name "*.yml" -exec bundle exec ruby -e "require 'yaml'; YAML.load_file('{}')" \;

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    
    - name: Run tests with coverage
      run: COVERAGE=true bundle exec rspec
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage/coverage.xml
        fail_ci_if_error: false

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    
    - name: Run bundle audit
      run: |
        gem install bundle-audit
        bundle audit check --update || true
    
    - name: Run brakeman (if applicable)
      run: |
        if bundle list | grep -q brakeman; then
          bundle exec brakeman --no-pager || true
        fi

  build:
    runs-on: ubuntu-latest
    needs: [test, lint, coverage]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    
    - name: Build gem
      run: |
        gem build rubocop-hk.gemspec
        ls -la *.gem
    
    - name: Test gem installation
      run: |
        gem install ./rubocop-hk-*.gem
        ruby -e "require 'rubocop-hk'; puts 'Gem loaded successfully'"
    
    - name: Upload gem artifact
      uses: actions/upload-artifact@v4
      with:
        name: rubocop-hk-gem
        path: "*.gem"