name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    
    - name: Run full test suite
      run: bundle exec rspec
    
    - name: Run RuboCop
      run: bundle exec rubocop --parallel

  build-and-publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    
    - name: Extract version from tag
      id: extract_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Build gem
      run: |
        gem build rubocop-hk.gemspec
        ls -la *.gem
    
    - name: Test gem installation
      run: |
        gem install ./rubocop-hk-*.gem
        ruby -e "require 'rubocop/hk'; puts Rubocop::Hk::VERSION"
    
    - name: Publish to RubyGems
      env:
        GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}
      run: |
        mkdir -p ~/.gem
        echo ":rubygems_api_key: $GEM_HOST_API_KEY" > ~/.gem/credentials
        chmod 600 ~/.gem/credentials
        gem push rubocop-hk-*.gem
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          rubocop-hk-*.gem
        body: |
          ## RuboCop HK v${{ steps.extract_version.outputs.VERSION }}
          
          See [CHANGELOG.md](CHANGELOG.md) for detailed changes.
          
          ### Installation
          
          ```bash
          gem install rubocop-hk -v "${{ steps.extract_version.outputs.VERSION }}"
          ```
          
          ### Quick Start
          
          ```yaml
          # .rubocop.yml
          inherit_gem:
            rubocop-hk: config/default.yml
          ```
        generate_release_notes: true
        make_latest: true

  notify:
    runs-on: ubuntu-latest
    needs: build-and-publish
    if: always()
    steps:
    - name: Notify success
      if: needs.build-and-publish.result == 'success'
      run: |
        echo "✅ Successfully released rubocop-hk ${GITHUB_REF#refs/tags/v}"
        echo "🎉 Available on RubyGems: https://rubygems.org/gems/rubocop-hk"
    
    - name: Notify failure
      if: needs.build-and-publish.result == 'failure'
      run: |
        echo "❌ Failed to release rubocop-hk ${GITHUB_REF#refs/tags/v}"
        echo "💡 Check the build logs for details"